### PR TITLE
Add MikroTik Cloud Hosted Router.

### PR DESCRIPTION
**Pull request by sig9org**
### Summary

Add MikroTik Cloud Hosted Router node definition.

### CODE REVIEW

**Comment by xorrkaz** [comment]
Thanks!  I love that we're having people contribute new node types.  A couple of things:

* I didn't see a QCOW2 image from the download site.  That's fine, it can be generated, but can you include the instructions in your readme as to which image to download and how to convert it to QCOW2?
* Can you include a sample image def that you used?

**Comment by sig9org** [comment]
@xorrkaz 

Thank you for your reply!
I fixed following:

1. The image conversion procedure of CHR was added.
2. Add CHR image definition.

Fixed the structure of the virl-base-images directory when adding the CHR image definition. Is that okay?

**Comment by xorrkaz** [comment]
Thanks!  Looks good.

**Comment by xorrkaz** [comment]
Ah, I missed it.  You didn't add your name to the Authors section in the root README.md.  Want to create a new PR to add it?

**Pull request merged**
